/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as appRouteRouteImport } from './routes/(app)/route'
import { Route as appIndexRouteImport } from './routes/(app)/index'
import { Route as appSettingsRouteImport } from './routes/(app)/settings'
import { Route as appSettingsIndexRouteImport } from './routes/(app)/settings/index'
import { Route as appSettingsLogsRouteImport } from './routes/(app)/settings/logs_'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const appRouteRoute = appRouteRouteImport.update({
  id: '/(app)',
  getParentRoute: () => rootRouteImport,
} as any)
const appIndexRoute = appIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => appRouteRoute,
} as any)
const appSettingsRoute = appSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => appRouteRoute,
} as any)
const appSettingsIndexRoute = appSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => appSettingsRoute,
} as any)
const appSettingsLogsRoute = appSettingsLogsRouteImport.update({
  id: '/logs_',
  path: '/logs',
  getParentRoute: () => appSettingsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/settings': typeof appSettingsRouteWithChildren
  '/': typeof appIndexRoute
  '/settings/logs': typeof appSettingsLogsRoute
  '/settings/': typeof appSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/': typeof appIndexRoute
  '/settings/logs': typeof appSettingsLogsRoute
  '/settings': typeof appSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(app)': typeof appRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/(app)/settings': typeof appSettingsRouteWithChildren
  '/(app)/': typeof appIndexRoute
  '/(app)/settings/logs_': typeof appSettingsLogsRoute
  '/(app)/settings/': typeof appSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/login' | '/settings' | '/' | '/settings/logs' | '/settings/'
  fileRoutesByTo: FileRoutesByTo
  to: '/login' | '/' | '/settings/logs' | '/settings'
  id:
    | '__root__'
    | '/(app)'
    | '/login'
    | '/(app)/settings'
    | '/(app)/'
    | '/(app)/settings/logs_'
    | '/(app)/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  appRouteRoute: typeof appRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)': {
      id: '/(app)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof appRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/': {
      id: '/(app)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof appIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/settings': {
      id: '/(app)/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof appSettingsRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/settings/': {
      id: '/(app)/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof appSettingsIndexRouteImport
      parentRoute: typeof appSettingsRoute
    }
    '/(app)/settings/logs_': {
      id: '/(app)/settings/logs_'
      path: '/logs'
      fullPath: '/settings/logs'
      preLoaderRoute: typeof appSettingsLogsRouteImport
      parentRoute: typeof appSettingsRoute
    }
  }
}

interface appSettingsRouteChildren {
  appSettingsLogsRoute: typeof appSettingsLogsRoute
  appSettingsIndexRoute: typeof appSettingsIndexRoute
}

const appSettingsRouteChildren: appSettingsRouteChildren = {
  appSettingsLogsRoute: appSettingsLogsRoute,
  appSettingsIndexRoute: appSettingsIndexRoute,
}

const appSettingsRouteWithChildren = appSettingsRoute._addFileChildren(
  appSettingsRouteChildren,
)

interface appRouteRouteChildren {
  appSettingsRoute: typeof appSettingsRouteWithChildren
  appIndexRoute: typeof appIndexRoute
}

const appRouteRouteChildren: appRouteRouteChildren = {
  appSettingsRoute: appSettingsRouteWithChildren,
  appIndexRoute: appIndexRoute,
}

const appRouteRouteWithChildren = appRouteRoute._addFileChildren(
  appRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  appRouteRoute: appRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
