/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as appRouteRouteImport } from './routes/(app)/route'
import { Route as appIndexRouteImport } from './routes/(app)/index'
import { Route as appSettingsRouteImport } from './routes/(app)/settings'
import { Route as appSettingsIndexRouteImport } from './routes/(app)/settings/index'
import { Route as appSettingsLogsRouteImport } from './routes/(app)/settings/logs_'
import { Route as appSettingsAuthRouteImport } from './routes/(app)/settings/auth_'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const appRouteRoute = appRouteRouteImport.update({
  id: '/(app)',
  getParentRoute: () => rootRouteImport,
} as any)
const appIndexRoute = appIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => appRouteRoute,
} as any)
const appSettingsRoute = appSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => appRouteRoute,
} as any)
const appSettingsIndexRoute = appSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => appSettingsRoute,
} as any)
const appSettingsLogsRoute = appSettingsLogsRouteImport.update({
  id: '/logs_',
  path: '/logs',
  getParentRoute: () => appSettingsRoute,
} as any)
const appSettingsAuthRoute = appSettingsAuthRouteImport.update({
  id: '/auth_',
  path: '/auth',
  getParentRoute: () => appSettingsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof appSettingsRouteWithChildren
  '/': typeof appIndexRoute
  '/settings/auth': typeof appSettingsAuthRoute
  '/settings/logs': typeof appSettingsLogsRoute
  '/settings/': typeof appSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/': typeof appIndexRoute
  '/settings/auth': typeof appSettingsAuthRoute
  '/settings/logs': typeof appSettingsLogsRoute
  '/settings': typeof appSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(app)': typeof appRouteRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/(app)/settings': typeof appSettingsRouteWithChildren
  '/(app)/': typeof appIndexRoute
  '/(app)/settings/auth_': typeof appSettingsAuthRoute
  '/(app)/settings/logs_': typeof appSettingsLogsRoute
  '/(app)/settings/': typeof appSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/settings'
    | '/'
    | '/settings/auth'
    | '/settings/logs'
    | '/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/'
    | '/settings/auth'
    | '/settings/logs'
    | '/settings'
  id:
    | '__root__'
    | '/(app)'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/(app)/settings'
    | '/(app)/'
    | '/(app)/settings/auth_'
    | '/(app)/settings/logs_'
    | '/(app)/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  appRouteRoute: typeof appRouteRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)': {
      id: '/(app)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof appRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/': {
      id: '/(app)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof appIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/settings': {
      id: '/(app)/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof appSettingsRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/settings/': {
      id: '/(app)/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof appSettingsIndexRouteImport
      parentRoute: typeof appSettingsRoute
    }
    '/(app)/settings/logs_': {
      id: '/(app)/settings/logs_'
      path: '/logs'
      fullPath: '/settings/logs'
      preLoaderRoute: typeof appSettingsLogsRouteImport
      parentRoute: typeof appSettingsRoute
    }
    '/(app)/settings/auth_': {
      id: '/(app)/settings/auth_'
      path: '/auth'
      fullPath: '/settings/auth'
      preLoaderRoute: typeof appSettingsAuthRouteImport
      parentRoute: typeof appSettingsRoute
    }
  }
}

interface appSettingsRouteChildren {
  appSettingsAuthRoute: typeof appSettingsAuthRoute
  appSettingsLogsRoute: typeof appSettingsLogsRoute
  appSettingsIndexRoute: typeof appSettingsIndexRoute
}

const appSettingsRouteChildren: appSettingsRouteChildren = {
  appSettingsAuthRoute: appSettingsAuthRoute,
  appSettingsLogsRoute: appSettingsLogsRoute,
  appSettingsIndexRoute: appSettingsIndexRoute,
}

const appSettingsRouteWithChildren = appSettingsRoute._addFileChildren(
  appSettingsRouteChildren,
)

interface appRouteRouteChildren {
  appSettingsRoute: typeof appSettingsRouteWithChildren
  appIndexRoute: typeof appIndexRoute
}

const appRouteRouteChildren: appRouteRouteChildren = {
  appSettingsRoute: appSettingsRouteWithChildren,
  appIndexRoute: appIndexRoute,
}

const appRouteRouteWithChildren = appRouteRoute._addFileChildren(
  appRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  appRouteRoute: appRouteRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
